Repository KCS-Second-Project/StepStory-Server, pull requests merged in 2024-03, with the labels that each got.

#14 ✨Spring Component Scan 관련 버그 수정/ 메인페이지 관련 api 구현 완료
  .gitignore
  .idea/dataSources.xml
  pom.xml
  src/main/java/com/kcs/stepstory/config/SwaggerConfig.java
  src/main/java/com/kcs/stepstory/controller/StepController.java
  src/main/java/com/kcs/stepstory/controller/TravelReportController.java
  src/main/java/com/kcs/stepstory/domain/TravelBody.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountDto.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountForAllDto.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountForBusanDto.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountForGyeonggiDto.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountForSeoulDto.java
  src/main/java/com/kcs/stepstory/dto/response/TravelReportDto.java
  src/main/java/com/kcs/stepstory/dto/response/TravelReportListDto.java
  src/main/java/com/kcs/stepstory/dto/response/UserDetailDto.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/repository/StepRepositoryCustom.java
  src/main/java/com/kcs/stepstory/repository/StepRepositoryCustomImpl.java
  src/main/java/com/kcs/stepstory/repository/TravelBodyRepository.java
  src/main/java/com/kcs/stepstory/security/config/SecurityConfig.java
  src/main/java/com/kcs/stepstory/security/handler/jwt/JwtAuthEntryPoint.java
  src/main/java/com/kcs/stepstory/security/handler/signout/CustomSignOutProcessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/signout/CustomSignOutResultHandler.java
  src/main/java/com/kcs/stepstory/service/StepService.java
  src/main/java/com/kcs/stepstory/service/TravelReportService.java
  src/main/webapp/WEB-INF/root-context.xml
  src/main/webapp/WEB-INF/servlet-context.xml
Labels: bug, feature, fix, 동겸

#15 🚑 Fix: 유저 회원가입 로직 및 테이블 컬럼명 수정, 닉네임 중복 확인 api 추가
  src/main/java/com/kcs/stepstory/controller/UserController.java
  src/main/java/com/kcs/stepstory/domain/User.java
  src/main/java/com/kcs/stepstory/dto/request/AuthSignUpDto.java
  src/main/java/com/kcs/stepstory/dto/request/UserUpdateDto.java
  src/main/java/com/kcs/stepstory/dto/response/UserDetailDto.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/repository/UserRepository.java
  src/main/java/com/kcs/stepstory/repository/custom/StepRepositoryCustom.java
  src/main/java/com/kcs/stepstory/repository/custom/StepRepositoryCustomImpl.java
  src/main/java/com/kcs/stepstory/security/handler/signin/DefaultSuccessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/signout/CustomSignOutProcessHandler.java
  src/main/java/com/kcs/stepstory/security/info/UserPrincipal.java
  src/main/java/com/kcs/stepstory/service/AuthService.java
  src/main/java/com/kcs/stepstory/service/UserService.java
Labels: feature, fix, 동겸

#18 🐛 Fix: 폼 로그인 버그 수정 완료
  src/main/java/com/kcs/stepstory/repository/UserRepository.java
  src/main/java/com/kcs/stepstory/security/handler/login/DefaultSuccessHandler.java
Labels: bug, fix, 동겸

#25 🐛 MariaDB PK auto_increment 속성을 사용하기 위한 PK 2개 -> 1개로 변경 및 Test시 오류 코드 수정
  src/main/java/com/kcs/stepstory/controller/TravelReportController.java
  src/main/java/com/kcs/stepstory/domain/Comment.java
  src/main/java/com/kcs/stepstory/domain/DetailCourse.java
  src/main/java/com/kcs/stepstory/domain/Friend.java
  src/main/java/com/kcs/stepstory/domain/Step.java
  src/main/java/com/kcs/stepstory/domain/TravelImage.java
  src/main/java/com/kcs/stepstory/domain/TravelReport.java
  src/main/java/com/kcs/stepstory/dto/request/PostTravelImageDto.java
  src/main/java/com/kcs/stepstory/dto/request/WriteCommentDto.java
  src/main/java/com/kcs/stepstory/dto/response/ViewCommentDto.java
  src/main/java/com/kcs/stepstory/repository/CommentRepository.java
  src/main/java/com/kcs/stepstory/repository/DetailCourseRepository.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/repository/TravelImageRepository.java
  src/main/java/com/kcs/stepstory/repository/WantToGoRepository.java
  src/main/java/com/kcs/stepstory/service/TravelReportService.java
Labels: 창희

#22 🐛✨ FIX: Auth 관련 API 엔드포인트 수정 및 메인페이지 Step관련 버그 수정/ Feat: 마이스토리 API 구현
  src/main/java/com/kcs/stepstory/controller/AuthController.java
  src/main/java/com/kcs/stepstory/controller/StepController.java
  src/main/java/com/kcs/stepstory/controller/TravelReportController.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/repository/TravelBodyRepository.java
  src/main/java/com/kcs/stepstory/repository/UserRepository.java
  src/main/java/com/kcs/stepstory/repository/custom/StepRepositoryCustom.java
  src/main/java/com/kcs/stepstory/repository/custom/StepRepositoryCustomImpl.java
  src/main/java/com/kcs/stepstory/security/config/SecurityConfig.java
  src/main/java/com/kcs/stepstory/service/StepService.java
  src/main/java/com/kcs/stepstory/service/TravelReportService.java
Labels: bug, fix, 동겸

#24 🎨:art: 친구관련 서비스 리팩토링 코드 변경
  src/main/java/com/kcs/stepstory/controller/FriendsController.java
  src/main/java/com/kcs/stepstory/controller/StepController.java
  src/main/java/com/kcs/stepstory/domain/Friend.java
  src/main/java/com/kcs/stepstory/dto/response/FriendDto.java
  src/main/java/com/kcs/stepstory/dto/response/StepCountForAllDto.java
  src/main/java/com/kcs/stepstory/repository/FriendRepository.java
  src/main/java/com/kcs/stepstory/repository/MyStepRepository.java
  src/main/java/com/kcs/stepstory/service/FriendsService.java
  src/main/java/com/kcs/stepstory/service/MyStepService.java
Labels: 인홍

#27 🚑 fix: 충돌 해결
  src/main/java/com/kcs/stepstory/dto/response/FriendListDto.java
  src/main/java/com/kcs/stepstory/repository/MyStepRepository.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/service/MyStepService.java
Labels: bug, fix, 동겸

#29 ✨ Image 파일 업로드 및 메타데이터 처리
  build.gradle
  src/main/java/com/kcs/stepstory/controller/TravelReportController.java
  src/main/java/com/kcs/stepstory/domain/TravelImage.java
  src/main/java/com/kcs/stepstory/dto/request/UploadTravelImageListDto.java
  src/main/java/com/kcs/stepstory/dto/response/CheckTravelImageDto.java
  src/main/java/com/kcs/stepstory/dto/response/ImageMetaDataDto.java
  src/main/java/com/kcs/stepstory/dto/response/ImageMetaDataListDto.java
  src/main/java/com/kcs/stepstory/dto/response/UploadImageMetaDataDto.java
  src/main/java/com/kcs/stepstory/service/TravelReportService.java
Labels: feature, 창희
