Repository KCS-Second-Project/StepStory-Server, pull requests merged in 2024-02, with the labels that each got.

#2 ✨Feat: 초기 세팅
  .gitignore
  .idea/.gitignore
  .idea/StepStory-Server.iml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  pom.xml
  src/main/webapp/WEB-INF/root-context.xml
  src/main/webapp/WEB-INF/servlet-context.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/index.jsp
Labels: feature, 동겸

#4 🚑 Feature: 로깅 추가
  pom.xml
Labels: feature, 동겸

#5 ✨feat: Spring JPA 개발 환경 설정
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/misc.xml
  pom.xml
  src/main/webapp/WEB-INF/root-context.xml
Labels: feature, 창희

#8 ✨feat:보일러 플레이트 설정
  src/main/java/com/kcs/stepstory/annotation/Date.java
  src/main/java/com/kcs/stepstory/annotation/UserId.java
  src/main/java/com/kcs/stepstory/config/SwaggerConfig.java
  src/main/java/com/kcs/stepstory/config/WebMVCConfig.java
  src/main/java/com/kcs/stepstory/config/temp
  src/main/java/com/kcs/stepstory/constants/Constants.java
  src/main/java/com/kcs/stepstory/constants/LocalDateValidator.java
  src/main/java/com/kcs/stepstory/contrant/temp
  src/main/java/com/kcs/stepstory/controller/AuthController.java
  src/main/java/com/kcs/stepstory/controller/temp
  src/main/java/com/kcs/stepstory/domain/User.java
  src/main/java/com/kcs/stepstory/domain/temp
  src/main/java/com/kcs/stepstory/dto/common/ArgumentNotValidExceptionDto.java
  src/main/java/com/kcs/stepstory/dto/common/ExceptionDto.java
  src/main/java/com/kcs/stepstory/dto/common/PageInfo.java
  src/main/java/com/kcs/stepstory/dto/common/ResponseDto.java
  src/main/java/com/kcs/stepstory/dto/request/AuthSignUpDto.java
  src/main/java/com/kcs/stepstory/dto/request/UserUpdateDto.java
  src/main/java/com/kcs/stepstory/dto/response/JwtTokenDto.java
  src/main/java/com/kcs/stepstory/dto/response/UserDetailDto.java
  src/main/java/com/kcs/stepstory/dto/temp
  src/main/java/com/kcs/stepstory/dto/type/EPaymentStatus.java
  src/main/java/com/kcs/stepstory/dto/type/EProvider.java
  src/main/java/com/kcs/stepstory/dto/type/ERole.java
  src/main/java/com/kcs/stepstory/dto/type/ErrorCode.java
  src/main/java/com/kcs/stepstory/exception/CommonException.java
  src/main/java/com/kcs/stepstory/exception/GlobalExceptionHandler.java
  src/main/java/com/kcs/stepstory/exception/temp
  src/main/java/com/kcs/stepstory/intercepter/post/ResponseInterceptor.java
  src/main/java/com/kcs/stepstory/intercepter/pre/UserIdArgumentResolver.java
  src/main/java/com/kcs/stepstory/intercepter/pre/UserIdInterceptor.java
  src/main/java/com/kcs/stepstory/intercepter/temp
  src/main/java/com/kcs/stepstory/repository/UserRepository.java
  src/main/java/com/kcs/stepstory/repository/temp
  src/main/java/com/kcs/stepstory/security/config/PasswordConfig.java
  src/main/java/com/kcs/stepstory/security/config/SecurityConfig.java
  src/main/java/com/kcs/stepstory/security/filter/GlobalLoggerFilter.java
  src/main/java/com/kcs/stepstory/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/kcs/stepstory/security/filter/JwtExceptionFilter.java
  src/main/java/com/kcs/stepstory/security/handler/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/kcs/stepstory/security/handler/jwt/JwtAuthEntryPoint.java
  src/main/java/com/kcs/stepstory/security/handler/signin/DefaultFailureHandler.java
  src/main/java/com/kcs/stepstory/security/handler/signin/DefaultSuccessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/singout/CustomSignOutProcessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/singout/CustomSignOutResultHandler.java
  src/main/java/com/kcs/stepstory/security/info/AbstractAuthenticationFailure.java
  src/main/java/com/kcs/stepstory/security/info/UserPrincipal.java
  src/main/java/com/kcs/stepstory/security/service/CustomUserDetailService.java
  src/main/java/com/kcs/stepstory/security/temp
  src/main/java/com/kcs/stepstory/service/AuthService.java
  src/main/java/com/kcs/stepstory/service/UserService.java
  src/main/java/com/kcs/stepstory/service/temp
  src/main/java/com/kcs/stepstory/utility/AuthCodeUtil.java
  src/main/java/com/kcs/stepstory/utility/CookieUtil.java
  src/main/java/com/kcs/stepstory/utility/HeaderUtil.java
  src/main/java/com/kcs/stepstory/utility/ImageUtil.java
  src/main/java/com/kcs/stepstory/utility/JwtUtil.java
  src/main/java/com/kcs/stepstory/utility/temp
Labels: feature, 동겸

#9 ✨ feat: 보일러 플레이트 설정
  .idea/dataSources.xml
  pom.xml
  src/main/java/com/kcs/stepstory/annotation/Date.java
  src/main/java/com/kcs/stepstory/annotation/UserId.java
  src/main/java/com/kcs/stepstory/config/SwaggerConfig.java
  src/main/java/com/kcs/stepstory/config/WebMVCConfig.java
  src/main/java/com/kcs/stepstory/constants/Constants.java
  src/main/java/com/kcs/stepstory/constants/LocalDateValidator.java
  src/main/java/com/kcs/stepstory/controller/AuthController.java
  src/main/java/com/kcs/stepstory/domain/User.java
  src/main/java/com/kcs/stepstory/dto/common/ArgumentNotValidExceptionDto.java
  src/main/java/com/kcs/stepstory/dto/common/ExceptionDto.java
  src/main/java/com/kcs/stepstory/dto/common/PageInfo.java
  src/main/java/com/kcs/stepstory/dto/common/ResponseDto.java
  src/main/java/com/kcs/stepstory/dto/request/AuthSignUpDto.java
  src/main/java/com/kcs/stepstory/dto/request/UserUpdateDto.java
  src/main/java/com/kcs/stepstory/dto/response/JwtTokenDto.java
  src/main/java/com/kcs/stepstory/dto/response/UserDetailDto.java
  src/main/java/com/kcs/stepstory/dto/type/EPaymentStatus.java
  src/main/java/com/kcs/stepstory/dto/type/EProvider.java
  src/main/java/com/kcs/stepstory/dto/type/ERole.java
  src/main/java/com/kcs/stepstory/dto/type/ErrorCode.java
  src/main/java/com/kcs/stepstory/exception/CommonException.java
  src/main/java/com/kcs/stepstory/exception/GlobalExceptionHandler.java
  src/main/java/com/kcs/stepstory/intercepter/post/ResponseInterceptor.java
  src/main/java/com/kcs/stepstory/intercepter/pre/UserIdArgumentResolver.java
  src/main/java/com/kcs/stepstory/intercepter/pre/UserIdInterceptor.java
  src/main/java/com/kcs/stepstory/repository/UserRepository.java
  src/main/java/com/kcs/stepstory/security/config/PasswordConfig.java
  src/main/java/com/kcs/stepstory/security/config/SecurityConfig.java
  src/main/java/com/kcs/stepstory/security/filter/GlobalLoggerFilter.java
  src/main/java/com/kcs/stepstory/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/kcs/stepstory/security/filter/JwtExceptionFilter.java
  src/main/java/com/kcs/stepstory/security/handler/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/kcs/stepstory/security/handler/jwt/JwtAuthEntryPoint.java
  src/main/java/com/kcs/stepstory/security/handler/signin/DefaultFailureHandler.java
  src/main/java/com/kcs/stepstory/security/handler/signin/DefaultSuccessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/singout/CustomSignOutProcessHandler.java
  src/main/java/com/kcs/stepstory/security/handler/singout/CustomSignOutResultHandler.java
  src/main/java/com/kcs/stepstory/security/info/AbstractAuthenticationFailure.java
  src/main/java/com/kcs/stepstory/security/info/UserPrincipal.java
  src/main/java/com/kcs/stepstory/security/service/CustomUserDetailService.java
  src/main/java/com/kcs/stepstory/service/AuthService.java
  src/main/java/com/kcs/stepstory/service/UserService.java
  src/main/java/com/kcs/stepstory/utility/AuthCodeUtil.java
  src/main/java/com/kcs/stepstory/utility/CookieUtil.java
  src/main/java/com/kcs/stepstory/utility/HeaderUtil.java
  src/main/java/com/kcs/stepstory/utility/ImageUtil.java
  src/main/java/com/kcs/stepstory/utility/JwtUtil.java
Labels: feature, 동겸

#11 ✨feat: domain class 생성
  src/main/java/com/kcs/stepstory/domain/Comment.java
  src/main/java/com/kcs/stepstory/domain/CommentId.java
  src/main/java/com/kcs/stepstory/domain/DetailCourse.java
  src/main/java/com/kcs/stepstory/domain/DetailCourseId.java
  src/main/java/com/kcs/stepstory/domain/Friend.java
  src/main/java/com/kcs/stepstory/domain/Step.java
  src/main/java/com/kcs/stepstory/domain/StepId.java
  src/main/java/com/kcs/stepstory/domain/TravelBody.java
  src/main/java/com/kcs/stepstory/domain/TravelImage.java
  src/main/java/com/kcs/stepstory/domain/TravelImageId.java
  src/main/java/com/kcs/stepstory/domain/TravelReport.java
  src/main/java/com/kcs/stepstory/domain/User.java
  src/main/java/com/kcs/stepstory/domain/WantToGo.java
  src/main/java/com/kcs/stepstory/domain/WantToGoId.java
  src/main/java/com/kcs/stepstory/repository/CommentRepository.java
  src/main/java/com/kcs/stepstory/repository/DetailCourseRepository.java
  src/main/java/com/kcs/stepstory/repository/FriendRepository.java
  src/main/java/com/kcs/stepstory/repository/StepRepository.java
  src/main/java/com/kcs/stepstory/repository/TravelBodyRepository.java
  src/main/java/com/kcs/stepstory/repository/TravelImageRepository.java
  src/main/java/com/kcs/stepstory/repository/TravelReportRepository.java
  src/main/java/com/kcs/stepstory/repository/WantToGoRepository.java
Labels: feature, 창희, 인홍
